services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./scripts:/app/scripts
    command: python scripts/load_data.py
    # command: python scripts/predict.py "This movie was fantastic!"
